### PR TITLE
Update to .Net Core

### PR DESCRIPTION
**Pull request by maksim789456**
Hello!
I ported your project to .Net core :)

### CODE REVIEW

**Comment by UweKeim** [comment]
Just for me to fully understand:

Is this based on .NET Standard? Or is it "just" .NET Core?

From my (shallow) understanding, a .NET Standard library runs both on .NET Full and .NET Core, whereas .NET Core only runs on .NET Core but not on .NET Full.

Can you clarify a little bit, please?

**Comment by maksim789456** [comment]
This is on .Net Core
Yes, you reason correctly
I forgot to put the .Net Standard when transferring

**Comment by UweKeim** [comment]
Possible to make it .NET Standard and submit another pull request?

Would be awesome!

**Comment by maksim789456** [comment]
> Possible to make it .NET Standard and submit another pull request?
> 
> Would be awesome!

https://github.com/UweKeim/ZetaIpc/pull/4

**Pull request merged**
