### PR TITLE
I'm sad...

### PR DESCRIPTION
**Pull request by maksim789456**
**Hi again.**
6 months have passed since my last pull request, and all these 6 months you did not make changes to the .net standard version. You forgot to receive changes after accepting my pull request #4. I tried to impose your changes on the state of the repository that I have left. I hope you understand and accept the pull request. And please do not push the changes through -f, --force.

### CODE REVIEW

**Comment by UweKeim** [comment]
Sorry, I am not _that_ into the GitHub best behaviours.

Since it shows here that there are conflicts, how should I start from here to get your pull requests correctly merged into the repository.

In addition, I am unsure what you refer to by ".NET Standard version", since IIRC my library is _not_ .NET Standard.

**Comment by maksim789456** [comment]
> In addition, I am unsure what you refer to by ".NET Standard version", since IIRC my library is not .NET Standard.
I transferred to .net standard
This is #4 pull request

>Since it shows here that there are conflicts, how should I start from here to get your pull requests correctly merged into the repository.
Most likely, you will have to perform a soft reset to commit a6913de and then accept pull request.

**Comment by UweKeim** [comment]
Thanks, I'll give it a try ASAP.

Is it really necessary that you added the ".vs" folder to the repo?

**Comment by maksim789456** [comment]
It happened by chance :)

**Comment by UweKeim** [comment]
I'll think I do prefer coyping and merging your changes manually so that I can avoid doing command line stuff and also avoid adding ".vs" files and things like that.

OK for you?

**Comment by maksim789456** [comment]
Yes, we can and so. Am I closing pull request?

**Comment by UweKeim** [comment]
Please keep it open, as a reminder to me.

**Comment by maksim789456** [comment]
Ok

**Comment by UweKeim** [comment]
I've now published the NuGet [version 1.0.0.9](https://www.nuget.org/packages/ZetaIpc/) and also updated the code here.

Could you please check whether the code is complete/working from your point of view?

**Comment by maksim789456** [comment]
Yes, in principle, everything is not bad. Thanks.
P.S. Then lay out another PR with some changes. Mainly aimed at the purity of the code.

**Pull request closed without merging**
